name: Build and Test Java Application

on:
  push:
    branches: [ "main" ]
    paths: [ '**.java', '.github/workflows/build.yaml', '.github/workflows/global-build.yaml','security.yaml', 'pom.xml' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run deploy'
        type: environment
        required: true
        default: 'dev'

jobs:
  build:
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/global-build.yaml@main
  security:
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/security.yaml@main
    needs: [ build ]
  push-image-to-docker-hub:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build, security ]
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest