name: Build and Test Java Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/global-build.yaml@main