name: Build and Test Java Application

on:
  push:
    branches: [ "main" ]
    paths: [ '**.java', '.github/workflows/build.yaml', '.github/workflows/global-build.yaml', 'pom.xml' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/global-build.yaml@main