name: Build and Test Java Application

on:
  push:
    branches: [ "main" ]
    paths: [ '**.java', '.github/workflows/build.yaml', '.github/workflows/global-build.yaml','security.yaml', 'pom.xml' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  build:
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/global-build.yaml@main
  security:
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/security.yaml@main
    needs: [ build ]
  push-image-to-docker-hub:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}

      - name: Docker Push
        run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}