name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: 'dev'
        description: 'Environment'
  push:
    branches:
      - main
env:
  USERNAME: gustavo

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Build and Test
        run: mvn test

      - name: Upload JaCoCo coverage report as a workflow artifact
        timeout-minutes: 2
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
  mutation-testing:
    name: Mutation Testing
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Run mutation testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage
  security-validation:
    name: Security Validation
    runs-on: ubuntu-22.04
    needs:
      - build
      - mutation-testing
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Run OWASP security validation
        run: mvn -B verify --file pom.xml -DskipTests
        continue-on-error: true

  push-to-docker-hub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-22.04
    environment: 'development'
    needs:
      - build
      - mutation-testing
      - security-validation
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: guhtiagosilva/github-actions-playground:latest


