name: Continuous Integration Pipeline

on:
  push:
    branches:
      - "solving-lab-1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        run: mvn test