name: Build and Test Java Application

on:
  push:
    branches:
      - "main"
    paths:
      - '**.java'
      - '.github/workflows/ci.yaml'
      - '.github/workflows/build.yaml'
      - 'security.yaml'
      - 'pom.xml'
  workflow_dispatch:
    inputs:
      environment:
        description: '(Dev, Staging, PRD)'
        type: environment
        default: 'dev'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/build.yaml@main
  mutation-testing:
    name: Mutation Testing
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/mutation-testing.yaml@main
    needs: [ build ]
  security:
    name: Security Validation
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/security.yaml@main
    needs: [ build, mutation-testing ]
  push-image-to-docker-hub:
    name: Push image to Docker Hub
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    needs: [ build, mutation-testing, security ]
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: guhtiagosilva/github-actions-playground:latest