name: Continuous Integration Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "solving-lab-1"

jobs:
  build:
    name: Build
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/build-and-test.yaml@solving-lab-1
  mutation-testing:
    name: Mutation Testing
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Run mutation testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage

      - name: Upload Mutation Testing Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: mutation-testing-report
          path: target/pit-reports/

  security:
    name: Security Analysis
    needs: [ build, mutation-testing ] ## TO run the security job, both build and mutation-testing must be completed
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/security.yaml

  push-image-to-docker-hub:
    name: Push image to Docker Hub
    environment: 'dev'
    runs-on: ubuntu-22.04
    needs: [ build, mutation-testing, security ] ## TO run the security job, both build, mutation-testing and security must be completed
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: guhtiagosilva/github-actions-playground:latest