name: Re-usable build java workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 5
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        timeout-minutes: 5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache the Maven packages to speed up build
        timeout-minutes: 5
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test with Maven
        timeout-minutes: 5
        run: mvn -B package --file pom.xml

      - name: Upload JaCoCo coverage report as a workflow artifact
        timeout-minutes: 5
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
  security:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP dependency vulnerability check
        run: mvn -B verify --file pom.xml -DskipTests
        timeout-minutes: 5