name: Re-usable build java workflow

## For a workflow to be reusable, the values for on must include workflow_call:
on:
  workflow_call:

jobs:
  build:
    name: Build and Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 5
      - name: Set up JDK
        uses: GuhTiagoSilva/github-actions-playground/.github/workflows/setup-java.yaml@main

      - name: Cache the Maven packages to speed up build
        timeout-minutes: 5
        uses: actions/cache@v1
        continue-on-error: true
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test with Maven
        timeout-minutes: 5
        run: mvn -B package --file pom.xml

      - name: Upload JaCoCo coverage report as a workflow artifact
        timeout-minutes: 5
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/