name: Continuous Integration - CI

on:
  push:
    branches:
      - main


jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Build and Test
        run: mvn test

      - name: Upload JaCoCo coverage report as a workflow artifact
        timeout-minutes: 2
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
  mutation-testing:
    name: Mutation Testing
    runs-on: ubuntu-22.04
    needs: [ build-and-test ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Mutation Testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage

  security-validation:
    name: Security Validation
    runs-on: ubuntu-22.04
    needs: [ build-and-test, mutation-testing ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Run security validation
        continue-on-error: true
        run: mvn -B verify --file pom.xml -DskipTests

  push-image-to-docker-hub:
    name: Push image to docker hub
    environment: 'dev'
    runs-on: ubuntu-22.04
    needs: [ build-and-test, mutation-testing, security-validation ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: guhtiagosilva/github-actions-playground:latest


