name: Pull Request Automation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    uses: GuhTiagoSilva/github-actions-playground/.github/workflows/build-and-test-global.yaml@main