name: Mutation Testing

on:
  workflow_call:

jobs:
  mutation-testing:
    name: Mutation Testing
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Run mutation testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage
