name: Security

on:
  workflow_call:

jobs:
  security:
    name: Deoendency Check Analysis
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 5

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Run OWASP dependency vulnerability check
        run: mvn -B verify --file pom.xml -DskipTests
        timeout-minutes: 5