name: Security

on:
  workflow_call:
    secrets:
      sonar-token:
        required: true
      sonar-host-url:
        required: true

env:
  SONAR_TOKEN: ${{ secrets.sonar-token }}
  SONAR_HOST_URL: ${{ secrets.sonar-host-url }}

jobs:
  security:
    name: Deoendency Check and Sonar Analysis
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 5

      - name: Run OWASP dependency vulnerability check
        run: mvn -B verify --file pom.xml -DskipTests
        timeout-minutes: 5
        continue-on-error: true

      - name: Print variables
        run: echo $SONAR_HOST_URL

      - name: Build and analyze
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=github-actions-playground -Dsonar.projectName='github-actions-playground'