name: Security Analysis

on:
  workflow_call:

jobs:
  security:
    runs-on: ubuntu-latest
    name: Security Analysis
    needs: [ build, mutation-testing ] ## TO run the security job, both build and mutation-testing must be completed
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Run OWASP dependency vulnerability check
        run: mvn -B verify --file pom.xml -DskipTests
        continue-on-error: true