name: Security

on:
  workflow_call:

jobs:
  security:
    name: Security
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 5
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        timeout-minutes: 5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run OWASP dependency vulnerability check
        run: mvn -B verify --file pom.xml -DskipTests
        timeout-minutes: 5

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=github-actions-playground -Dsonar.projectName='github-actions-playground'