name: Setup Java

on:
  workflow_call:
    inputs:
      java-version:
        type: number
        required: false
        default: 21

jobs:
  setup-java:
    name: Setup Java ${{ inputs.java-version }}
    runs-on: self-hosted
    timeout-minutes: 2

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven

